# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scriptLattesGUI.ui'
#
# Created: Thu Feb 27 13:43:00 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 791)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input = QtGui.QTextEdit(self.widget)
        self.input.setMaximumSize(QtCore.QSize(16777215, 25))
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.filechooser = QtGui.QPushButton(self.widget)
        self.filechooser.setMaximumSize(QtCore.QSize(16777215, 25))
        self.filechooser.setObjectName("filechooser")
        self.horizontalLayout.addWidget(self.filechooser)
        self.verticalLayout.addWidget(self.widget)
        self.runner = QtGui.QPushButton(self.centralwidget)
        self.runner.setObjectName("runner")
        self.verticalLayout.addWidget(self.runner)
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabs = QtGui.QTabWidget(self.widget_2)
        self.tabs.setObjectName("tabs")
        self.output_tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_tab.sizePolicy().hasHeightForWidth())
        self.output_tab.setSizePolicy(sizePolicy)
        self.output_tab.setAcceptDrops(False)
        self.output_tab.setObjectName("output_tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.output_tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollOutput = QtGui.QScrollArea(self.output_tab)
        self.scrollOutput.setWidgetResizable(True)
        self.scrollOutput.setObjectName("scrollOutput")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 887, 628))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.out = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.out.setObjectName("out")
        self.verticalLayout_3.addWidget(self.out)
        self.scrollOutput.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollOutput)
        self.tabs.addTab(self.output_tab, "")
        self.error_tab = QtGui.QWidget()
        self.error_tab.setObjectName("error_tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.error_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtGui.QScrollArea(self.error_tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 887, 628))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.errors = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.errors.setObjectName("errors")
        self.verticalLayout_5.addWidget(self.errors)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.tabs.addTab(self.error_tab, "")
        self.verticalLayout_2.addWidget(self.tabs)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ScriptLattes", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Escolha um arquivo de configuração", None, QtGui.QApplication.UnicodeUTF8))
        self.filechooser.setText(QtGui.QApplication.translate("MainWindow", "Escolher", None, QtGui.QApplication.UnicodeUTF8))
        self.runner.setText(QtGui.QApplication.translate("MainWindow", "Executar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.output_tab), QtGui.QApplication.translate("MainWindow", "Saída", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.error_tab), QtGui.QApplication.translate("MainWindow", "Erros", None, QtGui.QApplication.UnicodeUTF8))

